"""Organization structure, Members, roles, and authorization (permissions, defaults, overrides).

Revision ID: b89a71a2b1d0
Revises: 8335857d616c
Create Date: 2026-10-07 19:46:00.713477

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b89a71a2b1d0"
down_revision: str | Sequence[str] | None = "8335857d616c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ORG_UNIT_KIND_EXISTING: sa.types.TypeEngine[str] = postgresql.ENUM(
    "organization", "pmo", "administration", "team", name="org_unit_kind", create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_roles",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "unit_kind",
            sa.Enum("organization", "pmo", "administration", "team", name="org_unit_kind"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_org_roles")),
    )
    op.create_table(
        "permissions",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_permissions")),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("university_id", sa.String(length=64), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("major", sa.String(length=200), nullable=False),
        sa.Column("academic_year", sa.String(length=32), nullable=False),
        sa.Column("status", sa.Enum("active", "deactivated", name="member_status"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["user_accounts.id"], name=op.f("fk_members_account_id_user_accounts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_members")),
        sa.UniqueConstraint("account_id", name=op.f("uq_members_account_id")),
    )
    op.create_table(
        "org_units",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            # The type already exists (created with org_roles above).
            ORG_UNIT_KIND_EXISTING,
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.Enum("active", "archived", name="org_unit_status"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_by_account_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["archived_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_org_units_archived_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_org_units_created_by_account_id_user_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_units")),
    )
    op.create_index(
        "uq_org_units_single_organization",
        "org_units",
        ["kind"],
        unique=True,
        postgresql_where=sa.text("kind = 'organization'"),
    )
    op.create_index(
        "uq_org_units_single_pmo",
        "org_units",
        ["kind"],
        unique=True,
        postgresql_where=sa.text("kind = 'pmo'"),
    )
    op.create_table(
        "role_permission_defaults",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("role_key", sa.String(length=64), nullable=False),
        sa.Column("permission_key", sa.String(length=100), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=True),
        sa.Column("ended_by_account_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_role_permission_defaults_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_role_permission_defaults_created_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["ended_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_role_permission_defaults_ended_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["permission_key"],
            ["permissions.key"],
            name=op.f("fk_role_permission_defaults_permission_key_permissions"),
        ),
        sa.ForeignKeyConstraint(
            ["role_key"],
            ["org_roles.key"],
            name=op.f("fk_role_permission_defaults_role_key_org_roles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_permission_defaults")),
    )
    op.create_index(
        "uq_role_permission_defaults_open",
        "role_permission_defaults",
        ["role_key", "permission_key"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_table(
        "member_team_placements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("ended_by_account_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_member_team_placements_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_member_team_placements_created_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["ended_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_member_team_placements_ended_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_member_team_placements_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["org_units.id"], name=op.f("fk_member_team_placements_team_id_org_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_member_team_placements")),
    )
    op.create_index(
        op.f("ix_member_team_placements_member_id"),
        "member_team_placements",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_member_team_placements_team_id"),
        "member_team_placements",
        ["team_id"],
        unique=False,
    )
    op.create_index(
        "uq_member_team_placements_open",
        "member_team_placements",
        ["member_id"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_table(
        "org_unit_placements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=True),
        sa.Column("ended_by_account_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "unit_id <> parent_id", name=op.f("ck_org_unit_placements_not_own_parent")
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_org_unit_placements_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_org_unit_placements_created_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["ended_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_org_unit_placements_ended_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["org_units.id"], name=op.f("fk_org_unit_placements_parent_id_org_units")
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["org_units.id"], name=op.f("fk_org_unit_placements_unit_id_org_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_org_unit_placements")),
    )
    op.create_index(
        op.f("ix_org_unit_placements_parent_id"), "org_unit_placements", ["parent_id"], unique=False
    )
    op.create_index(
        op.f("ix_org_unit_placements_unit_id"), "org_unit_placements", ["unit_id"], unique=False
    )
    op.create_index(
        "uq_org_unit_placements_open",
        "org_unit_placements",
        ["unit_id"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_table(
        "permission_overrides",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("permission_key", sa.String(length=100), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("effect", sa.Enum("grant", "deny", name="override_effect"), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("ended_by_account_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "length(btrim(reason)) > 0", name=op.f("ck_permission_overrides_reason_required")
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_permission_overrides_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["user_accounts.id"],
            name=op.f("fk_permission_overrides_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_permission_overrides_created_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["ended_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_permission_overrides_ended_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["permission_key"],
            ["permissions.key"],
            name=op.f("fk_permission_overrides_permission_key_permissions"),
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["org_units.id"], name=op.f("fk_permission_overrides_unit_id_org_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permission_overrides")),
    )
    op.create_index(
        op.f("ix_permission_overrides_account_id"),
        "permission_overrides",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        "uq_permission_overrides_open",
        "permission_overrides",
        ["account_id", "permission_key", "unit_id", "effect"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_table(
        "role_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("role_key", sa.String(length=64), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("ended_by_account_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_role_assignments_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_role_assignments_created_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["ended_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_role_assignments_ended_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_role_assignments_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["role_key"], ["org_roles.key"], name=op.f("fk_role_assignments_role_key_org_roles")
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["org_units.id"], name=op.f("fk_role_assignments_unit_id_org_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_assignments")),
    )
    op.create_index(
        op.f("ix_role_assignments_member_id"), "role_assignments", ["member_id"], unique=False
    )
    op.create_index(
        op.f("ix_role_assignments_unit_id"), "role_assignments", ["unit_id"], unique=False
    )
    op.create_index(
        "uq_role_assignments_open",
        "role_assignments",
        ["member_id"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_role_assignments_open",
        table_name="role_assignments",
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.drop_index(op.f("ix_role_assignments_unit_id"), table_name="role_assignments")
    op.drop_index(op.f("ix_role_assignments_member_id"), table_name="role_assignments")
    op.drop_table("role_assignments")
    op.drop_index(
        "uq_permission_overrides_open",
        table_name="permission_overrides",
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.drop_index(op.f("ix_permission_overrides_account_id"), table_name="permission_overrides")
    op.drop_table("permission_overrides")
    op.drop_index(
        "uq_org_unit_placements_open",
        table_name="org_unit_placements",
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.drop_index(op.f("ix_org_unit_placements_unit_id"), table_name="org_unit_placements")
    op.drop_index(op.f("ix_org_unit_placements_parent_id"), table_name="org_unit_placements")
    op.drop_table("org_unit_placements")
    op.drop_index(
        "uq_member_team_placements_open",
        table_name="member_team_placements",
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.drop_index(op.f("ix_member_team_placements_team_id"), table_name="member_team_placements")
    op.drop_index(op.f("ix_member_team_placements_member_id"), table_name="member_team_placements")
    op.drop_table("member_team_placements")
    op.drop_index(
        "uq_role_permission_defaults_open",
        table_name="role_permission_defaults",
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.drop_table("role_permission_defaults")
    op.drop_index(
        "uq_org_units_single_pmo", table_name="org_units", postgresql_where=sa.text("kind = 'pmo'")
    )
    op.drop_index(
        "uq_org_units_single_organization",
        table_name="org_units",
        postgresql_where=sa.text("kind = 'organization'"),
    )
    op.drop_table("org_units")
    op.drop_table("members")
    op.drop_table("permissions")
    op.drop_table("org_roles")
    for enum_name in ("override_effect", "member_status", "org_unit_status", "org_unit_kind"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
