"""Access foundation: user accounts, auth sessions, login throttles, System Admin grants.

Revision ID: 8335857d616c
Revises:
Create Date: 2026-10-05 19:52:07.809311

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8335857d616c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_throttles",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("username", name=op.f("pk_login_throttles")),
    )
    op.create_table(
        "user_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("password_is_temporary", sa.Boolean(), nullable=False),
        sa.Column("temporary_password_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "deactivated", name="account_status"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_accounts")),
        sa.UniqueConstraint("username", name=op.f("uq_user_accounts_username")),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("csrf_token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "revoke_reason",
            sa.Enum(
                "sign_out",
                "sign_out_all",
                "password_change",
                "account_deactivated",
                name="session_revoke_reason",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["user_accounts.id"],
            name=op.f("fk_auth_sessions_account_id_user_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_auth_sessions_token_hash")),
    )
    op.create_index(
        op.f("ix_auth_sessions_account_id"), "auth_sessions", ["account_id"], unique=False
    )
    op.create_table(
        "system_admin_grants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("granted_by_account_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_account_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["user_accounts.id"],
            name=op.f("fk_system_admin_grants_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_system_admin_grants_granted_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_system_admin_grants_revoked_by_account_id_user_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_admin_grants")),
    )
    op.create_index(
        "uq_system_admin_grants_active_account",
        "system_admin_grants",
        ["account_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_system_admin_grants_active_account",
        table_name="system_admin_grants",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("system_admin_grants")
    op.drop_index(op.f("ix_auth_sessions_account_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_table("user_accounts")
    op.drop_table("login_throttles")
    sa.Enum(name="session_revoke_reason").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="account_status").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
