"""Announcements (versions, fixed recipients, version-aware reads) and in-app notifications.

Revision ID: 01947ff726ab
Revises: f2de4d1ebabc
Create Date: 2026-10-08 09:18:11.011800

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01947ff726ab"
down_revision: str | Sequence[str] | None = "f2de4d1ebabc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NOTIFICATION_CATEGORY_EXISTING: sa.types.TypeEngine[str] = postgresql.ENUM(
    "task_assignment",
    "task_update",
    "task_comment",
    "announcement_new",
    "announcement_change",
    name="notification_category",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "task_assignment",
                "task_update",
                "task_comment",
                "announcement_new",
                "announcement_change",
                name="notification_category",
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["user_accounts.id"],
            name=op.f("fk_notification_preferences_account_id_user_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preferences")),
        sa.UniqueConstraint(
            "account_id", "category", name=op.f("uq_notification_preferences_account_id")
        ),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipient_account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            # Created with notification_preferences above.
            NOTIFICATION_CATEGORY_EXISTING,
            nullable=False,
        ),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.String(length=300), nullable=True),
        sa.Column("actor_account_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_notifications_actor_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_notifications_recipient_account_id_user_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_recipient_visible",
        "notifications",
        ["recipient_account_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "announcements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope_unit_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("draft", "published", "withdrawn", name="announcement_state"),
            nullable=False,
        ),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_by_account_id", sa.Uuid(), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_by_account_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_announcements_created_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["published_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_announcements_published_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["scope_unit_id"],
            ["org_units.id"],
            name=op.f("fk_announcements_scope_unit_id_org_units"),
        ),
        sa.ForeignKeyConstraint(
            ["withdrawn_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_announcements_withdrawn_by_account_id_user_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcements")),
    )
    op.create_index(
        op.f("ix_announcements_scope_unit_id"), "announcements", ["scope_unit_id"], unique=False
    )
    op.create_table(
        "announcement_reads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("announcement_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["user_accounts.id"],
            name=op.f("fk_announcement_reads_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["announcements.id"],
            name=op.f("fk_announcement_reads_announcement_id_announcements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcement_reads")),
        sa.UniqueConstraint(
            "announcement_id",
            "account_id",
            "version",
            name=op.f("uq_announcement_reads_announcement_id"),
        ),
    )
    op.create_index(
        op.f("ix_announcement_reads_announcement_id"),
        "announcement_reads",
        ["announcement_id"],
        unique=False,
    )
    op.create_table(
        "announcement_recipients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("announcement_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["user_accounts.id"],
            name=op.f("fk_announcement_recipients_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["announcements.id"],
            name=op.f("fk_announcement_recipients_announcement_id_announcements"),
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_announcement_recipients_member_id_members")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcement_recipients")),
        sa.UniqueConstraint(
            "announcement_id", "member_id", name=op.f("uq_announcement_recipients_announcement_id")
        ),
    )
    op.create_index(
        op.f("ix_announcement_recipients_account_id"),
        "announcement_recipients",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_announcement_recipients_announcement_id"),
        "announcement_recipients",
        ["announcement_id"],
        unique=False,
    )
    op.create_table(
        "announcement_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("announcement_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["announcements.id"],
            name=op.f("fk_announcement_versions_announcement_id_announcements"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_announcement_versions_created_by_account_id_user_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcement_versions")),
        sa.UniqueConstraint(
            "announcement_id", "version", name=op.f("uq_announcement_versions_announcement_id")
        ),
    )
    op.create_index(
        op.f("ix_announcement_versions_announcement_id"),
        "announcement_versions",
        ["announcement_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_announcement_versions_announcement_id"), table_name="announcement_versions"
    )
    op.drop_table("announcement_versions")
    op.drop_index(
        op.f("ix_announcement_recipients_announcement_id"), table_name="announcement_recipients"
    )
    op.drop_index(
        op.f("ix_announcement_recipients_account_id"), table_name="announcement_recipients"
    )
    op.drop_table("announcement_recipients")
    op.drop_index(op.f("ix_announcement_reads_announcement_id"), table_name="announcement_reads")
    op.drop_table("announcement_reads")
    op.drop_index(op.f("ix_announcements_scope_unit_id"), table_name="announcements")
    op.drop_table("announcements")
    op.drop_index(
        "ix_notifications_recipient_visible",
        table_name="notifications",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("notifications")
    op.drop_table("notification_preferences")
    for enum_name in ("announcement_state", "notification_category"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
