"""Link series-generated subtasks to their subtask template (`tasks.series_template_key`).

Revision ID: f2de4d1ebabc
Revises: d7e3a1c9b5f2
Create Date: 2026-10-08 08:48:23.883474

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2de4d1ebabc"
down_revision: str | Sequence[str] | None = "d7e3a1c9b5f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("series_template_key", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "series_template_key")
    # ### end Alembic commands ###
