"""Account deactivation history (for historical access) and optional Member profile fields.

Revision ID: b11106c7034d
Revises: c4d2e8f1a7b3
Create Date: 2026-10-07 20:02:46.480424

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b11106c7034d"
down_revision: str | Sequence[str] | None = "c4d2e8f1a7b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_deactivations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "reactivated_at IS NULL OR reactivated_at > deactivated_at",
            name=op.f("ck_account_deactivations_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["user_accounts.id"],
            name=op.f("fk_account_deactivations_account_id_user_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_deactivations")),
    )
    op.create_index(
        op.f("ix_account_deactivations_account_id"),
        "account_deactivations",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        "uq_account_deactivations_open",
        "account_deactivations",
        ["account_id"],
        unique=True,
        postgresql_where=sa.text("reactivated_at IS NULL"),
    )
    # Accounts already deactivated get an open period from their last update (best known time).
    op.execute(
        "INSERT INTO account_deactivations (id, account_id, deactivated_at) "
        "SELECT gen_random_uuid(), id, updated_at FROM user_accounts WHERE status = 'deactivated'"
    )
    op.alter_column("members", "university_id", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.alter_column("members", "phone", existing_type=sa.VARCHAR(length=32), nullable=True)
    op.alter_column("members", "email", existing_type=sa.VARCHAR(length=254), nullable=True)
    op.alter_column("members", "major", existing_type=sa.VARCHAR(length=200), nullable=True)
    op.alter_column("members", "academic_year", existing_type=sa.VARCHAR(length=32), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for column in ("university_id", "phone", "email", "major", "academic_year"):
        op.execute(f"UPDATE members SET {column} = '' WHERE {column} IS NULL")
    op.alter_column("members", "academic_year", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.alter_column("members", "major", existing_type=sa.VARCHAR(length=200), nullable=False)
    op.alter_column("members", "email", existing_type=sa.VARCHAR(length=254), nullable=False)
    op.alter_column("members", "phone", existing_type=sa.VARCHAR(length=32), nullable=False)
    op.alter_column("members", "university_id", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.drop_index(
        "uq_account_deactivations_open",
        table_name="account_deactivations",
        postgresql_where=sa.text("reactivated_at IS NULL"),
    )
    op.drop_index(op.f("ix_account_deactivations_account_id"), table_name="account_deactivations")
    op.drop_table("account_deactivations")
    # ### end Alembic commands ###
