"""Tasks: tasks, scope history, assignments, comments, task-local events, weekly series.

Revision ID: 7eb2d45fba99
Revises: b11106c7034d
Create Date: 2026-10-07 23:35:36.435548

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7eb2d45fba99"
down_revision: str | Sequence[str] | None = "b11106c7034d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Created with task_series above; reused by tasks.
TASK_PRIORITY_EXISTING: sa.types.TypeEngine[str] = postgresql.ENUM(
    "low", "normal", "high", "urgent", name="task_priority", create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_series",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope_unit_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("low", "normal", "high", "urgent", name="task_priority"),
            nullable=True,
        ),
        sa.Column("assignee_member_ids", postgresql.ARRAY(sa.Uuid()), nullable=False),
        sa.Column("subtask_templates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "stopped", name="task_series_status"), nullable=False
        ),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_member_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_by_account_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("ends_at >= first_due_at", name=op.f("ck_task_series_ends_after_start")),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_task_series_created_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["members.id"],
            name=op.f("fk_task_series_created_by_member_id_members"),
        ),
        sa.ForeignKeyConstraint(
            ["scope_unit_id"], ["org_units.id"], name=op.f("fk_task_series_scope_unit_id_org_units")
        ),
        sa.ForeignKeyConstraint(
            ["stopped_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_task_series_stopped_by_account_id_user_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_series")),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "priority",
            TASK_PRIORITY_EXISTING,
            nullable=True,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("new", "in_progress", "completed", "cancelled", name="task_status"),
            nullable=False,
        ),
        sa.Column("scope_unit_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("series_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_member_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id <> id", name=op.f("ck_tasks_not_own_parent")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_tasks_created_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_member_id"],
            ["members.id"],
            name=op.f("fk_tasks_created_by_member_id_members"),
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["tasks.id"], name=op.f("fk_tasks_parent_id_tasks")),
        sa.ForeignKeyConstraint(
            ["scope_unit_id"], ["org_units.id"], name=op.f("fk_tasks_scope_unit_id_org_units")
        ),
        sa.ForeignKeyConstraint(
            ["series_id"], ["task_series.id"], name=op.f("fk_tasks_series_id_task_series")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(
        op.f("ix_tasks_created_by_member_id"), "tasks", ["created_by_member_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_parent_id"), "tasks", ["parent_id"], unique=False)
    op.create_index(op.f("ix_tasks_scope_unit_id"), "tasks", ["scope_unit_id"], unique=False)
    op.create_index(op.f("ix_tasks_series_id"), "tasks", ["series_id"], unique=False)
    op.create_table(
        "task_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("ended_by_account_id", sa.Uuid(), nullable=True),
        sa.Column(
            "end_reason",
            sa.Enum(
                "removed",
                "member_inactive",
                "out_of_scope",
                "series_update",
                name="task_assignment_end_reason",
            ),
            nullable=True,
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_task_assignments_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_task_assignments_created_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["ended_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_task_assignments_ended_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name=op.f("fk_task_assignments_member_id_members")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_assignments_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_assignments")),
    )
    op.create_index(
        op.f("ix_task_assignments_member_id"), "task_assignments", ["member_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_assignments_task_id"), "task_assignments", ["task_id"], unique=False
    )
    op.create_index(
        "uq_task_assignments_open",
        "task_assignments",
        ["task_id", "member_id"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.create_table(
        "task_comments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("author_account_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_task_comments_author_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_comments_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_comments")),
    )
    op.create_index(op.f("ix_task_comments_task_id"), "task_comments", ["task_id"], unique=False)
    op.create_table(
        "task_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("actor_account_id", sa.Uuid(), nullable=True),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_task_events_actor_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_events_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_events")),
        sa.UniqueConstraint("seq", name=op.f("uq_task_events_seq")),
    )
    op.create_index(op.f("ix_task_events_task_id"), "task_events", ["task_id"], unique=False)
    op.create_table(
        "task_scope_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_account_id", sa.Uuid(), nullable=False),
        sa.Column("ended_by_account_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name=op.f("ck_task_scope_history_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_task_scope_history_created_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["ended_by_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_task_scope_history_ended_by_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_scope_history_task_id_tasks")
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["org_units.id"], name=op.f("fk_task_scope_history_unit_id_org_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_scope_history")),
    )
    op.create_index(
        op.f("ix_task_scope_history_task_id"), "task_scope_history", ["task_id"], unique=False
    )
    op.create_index(
        "uq_task_scope_history_open",
        "task_scope_history",
        ["task_id"],
        unique=True,
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_task_scope_history_open",
        table_name="task_scope_history",
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.drop_index(op.f("ix_task_scope_history_task_id"), table_name="task_scope_history")
    op.drop_table("task_scope_history")
    op.drop_index(op.f("ix_task_events_task_id"), table_name="task_events")
    op.drop_table("task_events")
    op.drop_index(op.f("ix_task_comments_task_id"), table_name="task_comments")
    op.drop_table("task_comments")
    op.drop_index(
        "uq_task_assignments_open",
        table_name="task_assignments",
        postgresql_where=sa.text("valid_to IS NULL"),
    )
    op.drop_index(op.f("ix_task_assignments_task_id"), table_name="task_assignments")
    op.drop_index(op.f("ix_task_assignments_member_id"), table_name="task_assignments")
    op.drop_table("task_assignments")
    op.drop_index(op.f("ix_tasks_series_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_scope_unit_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_parent_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_created_by_member_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("task_series")
    for enum_name in (
        "task_assignment_end_reason",
        "task_status",
        "task_series_status",
        "task_priority",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
